trigger: 
- main

pool:
  vmImage: ubuntu-latest

variables:
  tag: 1.0.0-$(Build.BuildId)
  acr_name: acrcicdaks

steps:
- task: AzureCLI@2
  displayName: Docker Build & Push
  inputs:
    azureSubscription: 'Assinatura de Plataformas MSDN(4ee6b987-e149-41bb-b8a5-39216f3677aa)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t $(acr_name).azurecr.io/webapp:$(tag) app-dotnet
      az acr login -n $(acr_name)
      docker push $(acr_name).azurecr.io/webapp:$(tag)

- task: replacetokens@6
  displayName: 'Replace Image TAG'
  inputs:
    root: '02_kubernetes_aks'
    sources: 'app-deploy.yaml'
    tokenPattern: 'doubleunderscores'

- script: cat 02_kubernetes_aks/app-deploy.yaml
  displayName: View app-deploy.yaml

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Assinatura de Plataformas MSDN(4ee6b987-e149-41bb-b8a5-39216f3677aa)'
    azureResourceGroup: 'rg-cicd-yaml-aks'
    kubernetesCluster: 'aks-cluster-cicd'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '02_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'


